### ISSUE TITLE
Issue running with latest node plugin

### ISSUE THREAD

**Issue by michaelruocco** [michaelruocco/gradle-postman-runner#10]
Hi, I have attempted to use this plugin with the latest version of the node gradle plugin (1.3.1) and I am getting a class not found exception thrown:

```
java.lang.NoClassDefFoundError: com/moowork/gradle/node/task/NpmTask
        at de.infonautika.postman.PostmanRunnerPlugin.createTasks(PostmanRunnerPlugin.java:32)
        at de.infonautika.postman.PostmanRunnerPlugin.apply(PostmanRunnerPlugin.java:20)
        at de.infonautika.postman.PostmanRunnerPlugin.apply(PostmanRunnerPlugin.java:12)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:181)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:276)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
```

etc... (I can post the full stack trace if it would be helpful.

From looking at the latest source code here: https://github.com/srs/gradle-node-plugin/tree/master/src/main/groovy/com/moowork/gradle/node/npm, it looks like the NpmTask has been separated into a new package, i.e. com.moowork.gradle.node.npm.NpmTask, however the current version of the plugin is looking for com.moowork.gradle.node.task.NpmTask.

I have confirmed this by rolling back to version 0.14 of the node gradle plugin as this was the latest version that I could find that would work (I am guessing the package move happened on the major version upgrade) after this everything works fine. To that end I already have a temporary work around, but I wanted to ask if you were thinking of updating to work with the latest (1.3.1) or a newer version anytime soon? If not I might have a look at raising a PR myself if I can find the time.

Thanks!

**Comment by michaelruocco** [comment]
fixed

**Comment by TheGabCode** [comment]
Hello, how was this fixed? I've come across the same issue. Do I just roll back to 0.14 of the node gradle plugin?

**Comment by michaelruocco** [comment]
@TheGabCode that was what I did originally, however I have now taken ownership of this repo and I applied the fix myself, the new latest version is here:

https://plugins.gradle.org/plugin/com.github.michaelruocco.gradle-postman-runner

Please try upgrading to this version and let me know if you run into any issues.
